#!/usr/bin/env bash
# Interactive helper for rotation-schedule.json (this repo's own root
# -- see its own "_comment" and README.md's Rotation section). GitHub
# renders .json files as syntax-highlighted code, never as Markdown,
# and plain GFM tables have no built-in column sort -- so this bakes
# the "soonest to expire first" order in at generation time instead,
# into a real Markdown table (rotation-schedule.md) that's pleasant to
# browse on GitHub.
#
# Usage:
#   ./scripts/manage-rotation-schedule.sh
#       Interactive: lists every secret, asks which one was just
#       rotated, sets its last_rotated to today in rotation-schedule.json,
#       then regenerates rotation-schedule.md.
#
#   ./scripts/manage-rotation-schedule.sh --render-only
#       Regenerates rotation-schedule.md only -- no prompt, no date
#       changes. Useful after editing rotation-schedule.json by hand
#       (e.g. adding a new secret) without rotating anything.
#
# Never touches the real credential or AWS -- this only edits the
# tracking file and its own rendered view. Rotate the real secret
# first (see the runbook_url this same file points at), then run this.

set -euo pipefail

schedule_file="rotation-schedule.json"
markdown_file="rotation-schedule.md"

fail() {
  echo "manage-rotation-schedule: $1" >&2
  exit 1
}

command -v jq >/dev/null || fail "jq not found"
[ -f "${schedule_file}" ] || fail "${schedule_file} not found"

render_only=false
if [ "${1:-}" = "--render-only" ]; then
  render_only=true
elif [ -n "${1:-}" ]; then
  fail "unknown argument '${1}' (only --render-only is supported)"
fi

count="$(jq '.secrets | length' "${schedule_file}")"

if [ "${render_only}" = false ]; then
  echo "Which secret was just rotated?"
  echo
  for i in $(seq 0 $((count - 1))); do
    id="$(jq -r ".secrets[${i}].id" "${schedule_file}")"
    printf '  %3d) %s\n' "$((i + 1))" "${id}"
  done
  echo

  read -rp "Enter number (or Ctrl-C to cancel): " choice
  case "${choice}" in
  '' | *[!0-9]*) fail "'${choice}' is not a number" ;;
  esac
  [ "${choice}" -ge 1 ] && [ "${choice}" -le "${count}" ] || fail "'${choice}' is out of range (1-${count})"

  index=$((choice - 1))
  id="$(jq -r ".secrets[${index}].id" "${schedule_file}")"
  today="$(date -u +%F)"

  tmp_schedule="$(mktemp)"
  jq --indent 2 --argjson idx "${index}" --arg today "${today}" \
    '.secrets[$idx].last_rotated = $today' "${schedule_file}" >"${tmp_schedule}"
  mv "${tmp_schedule}" "${schedule_file}"

  echo "Updated ${id}: last_rotated -> ${today}"
  echo
fi

echo "Regenerating ${markdown_file}..."

generated_on="$(date -u +%F)"
tmp_rows="$(mktemp)"
trap 'rm -f "${tmp_rows}"' EXIT

for i in $(seq 0 $((count - 1))); do
  entry="$(jq -c ".secrets[${i}]" "${schedule_file}")"
  id="$(echo "${entry}" | jq -r '.id')"
  description="$(echo "${entry}" | jq -r '.description')"
  runbook_url="$(echo "${entry}" | jq -r '.runbook_url')"
  last_rotated="$(echo "${entry}" | jq -r '.last_rotated')"
  interval="$(echo "${entry}" | jq -r '.rotate_every_days')"

  # next_due is an absolute date -- unlike a "days left" count, it stays
  # equally meaningful whether this file was regenerated today or months
  # ago (this script has no schedule of its own; check-secret-rotation.yml
  # is what actually watches this daily). Sorted on directly below, not a
  # separately-computed days-left number: it's already YYYY-MM-DD, so a
  # plain lexicographic sort is already a correct chronological one.
  next_due="$(date -u -d "${last_rotated} +${interval} days" +%F)" \
    || fail "${id}: invalid last_rotated/rotate_every_days"

  # Escape the one character that would actually break a table cell --
  # a literal "|" -- everything else (backticks, parens) is fine as-is.
  description="${description//|/\\|}"

  printf '%s\t%s\t%s\t%s\t%s\n' \
    "${next_due}" "${id}" "${last_rotated}" "${description}" "${runbook_url}" \
    >>"${tmp_rows}"
done

{
  echo "<!-- Generated by scripts/manage-rotation-schedule.sh from rotation-schedule.json."
  echo "     Do not edit by hand -- edit that file (or run this script) and re-run instead. -->"
  echo
  echo "# Secret rotation schedule"
  echo
  echo "Generated ${generated_on}. Sorted soonest-due first -- compare \"Next" \
    "due\" against today's own date to see what's overdue; this file has no" \
    "schedule of its own, so a relative day-count here would go stale the" \
    "moment time passes without a re-run (check-secret-rotation.yml is what" \
    "actually watches this daily). Machine-readable source:" \
    "[rotation-schedule.json](rotation-schedule.json). Full mechanism:" \
    "[README.md](README.md)'s own Rotation section."
  echo
  echo "| Next due | Secret | Last rotated | Description | Runbook |"
  echo "|---|---|---|---|---|"
  sort -t "$(printf '\t')" -k1,1 "${tmp_rows}" | while IFS="$(printf '\t')" read -r next_due id last_rotated description runbook_url; do
    printf '| %s | `%s` | %s | %s | [link](%s) |\n' \
      "${next_due}" "${id}" "${last_rotated}" "${description}" "${runbook_url}"
  done
} >"${markdown_file}"

echo "Wrote ${markdown_file}"
